### ISSUE TITLE
How to run model

### ISSUE THREAD

**Issue by HappyDay-design** [jjkysy/Traffic-estimation-and-evaluation#1]
Hello
Thank you very much

I run
`python runner1.py`

(Hung) osboxes@osboxes:~/Desktop/Traffic-estimation-and-evaluation$ /home/osboxes/anaconda3/envs/Hung/bin/python /home/osboxes/Desktop/Traffic-estimation-and-evaluation/runner1.py
> /home/osboxes/Desktop/Traffic-estimation-and-evaluation/runner1.py(103)main()
-> traci.start([sumoBinary, "-c", "data/cross1.sumocfg", "--step-length", str(time_step),
(Pdb) 

I do not know how to continue to run your models

**Comment by jjkysy** [comment]
just type a preferred step length (e.g. 0.1, 1, etc.) in any IDE you use, and press ' Enter '. Of course, you can always delete pdb.set_trace(), it's just for debugging... This script is only an example of traffic flow modelling and estimation.
